FROM ann-benchmarks

RUN git clone https://github.com/lyst/rpforest
RUN cd rpforest && python3 setup.py install
RUN python3 -c 'import rpforest'
RUN pip3 install datasketch
RUN python3 -c 'import datasketch'
