FROM ann-benchmarks

RUN git clone https://github.com/ipsarros/DolphinnPy lib-dolphinnpy
ENV PYTHONPATH lib-dolphinnpy
RUN python3 -c 'import dolphinn'
RUN pip3 install datasketch
RUN python3 -c 'import datasketch'
